### ISSUE TITLE
node list: TypeError

### ISSUE THREAD

**Issue by Cynerd** [hardwario/bch-control-tool#1]
```
root@turris:~# bch node list
Traceback (most recent call last):
  File "/usr/bin/bch", line 8, in <module>
    load_entry_point('bch', 'console_scripts', 'bch')()
  File "/usr/lib/python3.6/site-packages/bch/cli.py", line 106, in main
    cli(obj={})
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/bch/node.py", line 33, in node_list
    rows = [[node['id'], node.get('alias', '')] for node in nodes]
  File "/usr/lib/python3.6/site-packages/bch/node.py", line 33, in <listcomp>
    rows = [[node['id'], node.get('alias', '')] for node in nodes]
TypeError: string indices must be integers

```

Output from `mosquitto_sub -v -t '#'`:
```
gateway/usb-dongle/nodes/get null
gateway/usb-dongle/nodes ["69703fb2cbe5", "e636fb0b8c99", "9c33bd95fa2e", "6590f027809a", "83913187f959"]
```

**Comment by hubmartin** [comment]
Hello,
this seems like you have old version of `bcg`. The new one returns little bit different MQTT response with `id` and `alias`.

This is my response when I type `bch node list`:

"[{"id": "836d1983890a", "alias": "pool"}, {"id": "836d1983075a", "alias": "bedroom"}, {"id": "836d1983532f", "alias": "livingroom"}]"

Please, try to update `bcg` (https://www.bigclown.com/doc/tools/bcg/) and reboot system or the running service by `pm2 restart bcg-ud`

**Comment by Cynerd** [comment]
Yes you are right. Sorry that was my fault. I ended up with 1.9.1 version of `bcg` because of `sort` vs. `sort -V`.

I have updated to newest version and now it does not fail.
